#!/usr/bin/env python

# Copyright (c) 2019 Computer Vision Center (CVC) at the Universitat Autonoma de
# Barcelona (UAB).
#
# This work is licensed under the terms of the MIT license.
# For a copy, see <https://opensource.org/licenses/MIT>.

import glob
import os
import sys


print('here')
try:
    sys.path.append(glob.glob('../carla/dist/carla-*%d.%d-%s.egg' % (
        sys.version_info.major,
        sys.version_info.minor,
        'win-amd64' if os.name == 'nt' else 'linux-x86_64'))[0])
    print('enter try')
    print(sys.path)

except IndexError:
    pass

print('here2')

import carla
print('Carla imported')

import random


def main():
    actor_list = []

    # In this tutorial script, we are going to add a vehicle to the simulation
    # and let it drive in autopilot. We will also create a camera attached to
    # that vehicle, and save all the images generated by the camera to disk.

    try:
        # First of all, we need to create the client that will send the requests
        # to the simulator. Here we'll assume the simulator is accepting
        # requests in the localhost at port 2000.

        client = carla.Client('localhost', 2000)
        client.set_timeout(2.0)
        print('created client')

        # Once we have a client we can retrieve the world that is currently
        # running.
        world = client.get_world()

        print('Imported world')

        # === SYNCHRONOUS MODE ===
        original_settings = world.get_settings()
        settings = world.get_settings()
        settings.synchronous_mode = True
        settings.fixed_delta_seconds = 1.0 / 20  # 20 Hz, car lidar_rotation_frequency = 20
        world.apply_settings(settings)


        # The world contains the list blueprints that we can use for adding new
        # actors into the simulation.
        blueprint_library = world.get_blueprint_library()

        bp = blueprint_library.find('vehicle.tesla.model3')

        # Now we need to give an initial transform to the vehicle. We choose a
        # random transform from the list of recommended spawn points of the map.
        transform = random.choice(world.get_map().get_spawn_points())

        # So let's tell the world to spawn the vehicle.
        vehicle = world.spawn_actor(bp, transform)

        # It is important to note that the actors we create won't be destroyed
        # unless we call their "destroy" function. If we fail to call "destroy"
        # they will stay in the simulation even after we quit the Python script.
        # For that reason, we are storing all the actors we create so we can
        # destroy them afterwards.
        actor_list.append(vehicle)
        print('created %s' % vehicle.type_id)

        # Let's put the vehicle to drive around.
        vehicle.set_autopilot(True)


        # === LiDAR 1 ===
        lidar1_bp = blueprint_library.find('sensor.lidar.ray_cast')
        lidar1_bp.set_attribute('range', '100')
        lidar1_bp.set_attribute('rotation_frequency', '20')
        lidar1_bp.set_attribute('channels', '32')
        lidar1_bp.set_attribute('points_per_second', '100000')
        lidar1_bp.set_attribute('noise_stddev', '0')

        lidar1_transform = carla.Transform(carla.Location(x=0.0, z=2.0))
        lidar1 = world.spawn_actor(lidar1_bp, lidar1_transform, attach_to=vehicle)
        actor_list.append(lidar1)
        print('created LiDAR 1: %s' % lidar1.type_id)

        # === LiDAR 2 ===
        lidar2_bp = blueprint_library.find('sensor.lidar.ray_cast_complete')
        lidar2_bp.set_attribute('range', '50')
        lidar2_bp.set_attribute('rotation_frequency', '20')
        lidar2_bp.set_attribute('channels', '64')
        lidar2_bp.set_attribute('points_per_second', '100000')
        lidar2_bp.set_attribute('noise_stddev', '0.5')

        lidar2_transform = carla.Transform(carla.Location(x=0.0, z=2.0))
        lidar2 = world.spawn_actor(lidar2_bp, lidar2_transform, attach_to=vehicle)
        actor_list.append(lidar2)
        print('created LiDAR 2: %s' % lidar2.type_id)


        # Ajoute un objet pour visualiser où est le LiDAR
        #lidar_vis_bp = blueprint_library.find('static.prop.trafficcone01')
        #lidar_vis = world.spawn_actor(lidar_vis_bp, lidar_transform, attach_to=vehicle)
        #actor_list.append(lidar_vis)

        # === LIDAR SAVE SETUP ===
        from queue import Queue

        lidar1_queue = Queue()
        lidar2_queue = Queue()

        lidar1.listen(lambda data: lidar1_queue.put(data))
        lidar2.listen(lambda data: lidar2_queue.put(data))

        home = os.path.expanduser("~")
        save_path1 = os.path.join(home, "data/lidar1_%06d.ply")
        save_path2 = os.path.join(home, "data2/lidar2_%06d.ply")

        os.makedirs(os.path.dirname(save_path1), exist_ok=True)
        os.makedirs(os.path.dirname(save_path2), exist_ok=True)

        # === RUN SIMULATION FOR N STEPS ===
        for _ in range(400): # on aura donc 400 images car fixed_delta_seconds est à 0.05, une frequence de 20hz
            world.tick()

            if not lidar1_queue.empty():
                pc1 = lidar1_queue.get()
                pc1.save_to_disk(save_path1 % pc1.frame)

            if not lidar2_queue.empty():
                pc2 = lidar2_queue.get()
                pc2.save_to_disk(save_path2 % pc2.frame)

    # === CLEANUP ===
    finally:
        print('destroying actors')

        for lidar in [lidar1, lidar2]:
            if lidar.is_alive:
                lidar.stop()

        # Détruire tous les acteurs
        for actor in actor_list:
            if actor.is_alive:
                actor.destroy()

        # Remettre les settings initiaux
        world.apply_settings(original_settings)
        print('done.')

    


if __name__ == '__main__':

    main()